### ISSUE TITLE
how to apply custom font. . ?

### ISSUE THREAD

**Issue by fahad-mukhtar** [Chivorns/SmartMaterialSpinner#10]
how to apply custom font. . ?

**Comment by Chivorns** [comment]
Hi @fahad-mukhtar . Currently I'm adding this feature in next release. Please stay tune. Thank you.

**Comment by Chivorns** [comment]
Hi @fahad-mukhtar , I have done for this request. It will available in next release soon.

**Comment by Chivorns** [comment]
Hi @fahad-mukhtar, you request is available in version 1.2.1 now. Please enjoy!
