### ISSUE TITLE
How to clear selection ?

### ISSUE THREAD

**Issue by SalihCanBinboga** [Chivorns/SmartMaterialSpinner#14]
How to clear selection ?

**Comment by Chivorns** [comment]
Hi @SalihCanBinboga please help to detail on your question. Thank

**Comment by SalihCanBinboga** [comment]
I use "clearselection ()" but it doesn't work.

**Comment by mooglife** [comment]
clearselection() is working fine for me.

**Comment by SalihCanBinboga** [comment]
@mooglife yes working but partially so problem: selectedcolor don't clear i can use clearselection() selection clear but still row selected color active

**Comment by Chivorns** [comment]
Hi @SalihCanBinboga , so the issue is about selected color not clear when you clear selection?

**Comment by SalihCanBinboga** [comment]
@Chivorns yes true when can use clearselection but not clear selected color

**Comment by mooglife** [comment]
@SalihCanBinboga I am unable to replicate this behaviour. for clearselection() clears the selected color as well. I tested both "legacy" and "androidx" versions. works well!

**Comment by SalihCanBinboga** [comment]
@mooglife can u send me related part ?

**Comment by mooglife** [comment]
@SalihCanBinboga  I am not sure if this helps you...but call to clearselection(), kinds of, resets the spinner and selected color too.

this is the sample code for your: 

`public class Location extends AppCompatActivity {
    public SmartMaterialSpinner countrySpinner;
    public List<String> countryList;
    public String country="xyz";
    public TextView clearselection;

    public void onCreate(Bundle icicle) {
        super.onCreate(icicle);
        setContentView(R.layout.location);
        countrySpinner = findViewById(R.id.countryspinner);

        clearselection = findViewById(R.id.clearselection);
        clearselection.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                clearSelection();
            }
        });

        initSpinner();
    }


    private void clearSelection(){
        countrySpinner.clearSelection();
        clearselection.setVisibility(GONE);
    }


    private void initSpinner() {

        countryList = new ArrayList<>();
        MyCountries mc = new MyCountries();
        int position = 0;
        for (int i = 0; i < mc.countries.length; i++){
            countryList.add(mc.countries[i]);
            if(country.equals(mc.countries[i])) position=i;
        }

        countrySpinner.setItem(countryList);
        if(position!=0){
            countrySpinner.setSelection(position);
        }

        countrySpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> adapterView, View view, int position, long id) {
                country = countryList.get(position);
                clearselection.setVisibility(View.VISIBLE);
            }
        });
    }

}`

**Comment by SalihCanBinboga** [comment]
@mooglife this screen record video on emulator https://vimeo.com/402557753
this about code ;

`import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.View
import android.widget.AdapterView
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        loadSpinner()

        clearselection.setOnClickListener {
            clearSelection()
        }
    }

    private fun loadSpinner() {
        val testList = ArrayList<String>()
        testList.add("test1")
        testList.add("test2")
        testList.add("test3")
        testList.add("test4")

        countrySpinner.item = testList
        countrySpinner.onItemSelectedListener = object : AdapterView.OnItemSelectedListener{
            override fun onNothingSelected(parent: AdapterView<*>?) {
                countrySpinner.clearSelection()
            }

            override fun onItemSelected(parent: AdapterView<*>?, view: View?, position: Int, id: Long) {
                clearselection.text = testList[position]
            }

        }
    }

    private fun clearSelection() {
        countrySpinner.clearSelection()
    }
}`

XML:

`<com.chivorn.smartmaterialspinner.SmartMaterialSpinner
        android:id="@+id/countrySpinner"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="16dp"
        app:layout_constraintBottom_toTopOf="@+id/clearselection"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"

        app:smsp_isSearchable="true"
        app:smsp_searchHeaderText="TEST HEADER"
        app:smsp_searchHeaderTextColor="#FF5722"
        app:smsp_searchHeaderBackgroundColor="#E91E63"
        app:smsp_searchHint="SEARCH HİNT"
        app:smsp_searchHintColor="#8BC34A"
        app:smsp_searchTextColor="#000000"

        app:smsp_itemSize="16sp"
        app:smsp_itemColor="#512DA8"

        app:smsp_hint="HİNT TEXT"
        app:smsp_hintSize="16sp"
        app:smsp_hintColor="#388E3C"
        app:smsp_itemListColor="#7C4DFF"
        app:smsp_itemListHintBackgroundColor="#808080"

        app:smsp_enableErrorLabel="false"
        app:smsp_arrowColor="#FF6E6E"

        app:smsp_underlineColor="#3F51B5"
        app:smsp_underlineSize="4dp"

        app:smsp_floatingLabelColor="#1976D2"
        app:smsp_floatingLabelText="Floating Label Text"
        app:smsp_itemListHintColor="#FFFFFF"
        app:smsp_multilineError="false"
        app:smsp_selectedItemListColor="#FF5252" />`

**Comment by Chivorns** [comment]
Hi @SalihCanBinboga , thank for your feedback on this. I also can replicate this issue yesterday. And it happened only for searchable mode. I will include this fix in next release soon as currently I also working on other new feature request and issues too.
Please stay tune!

**Comment by Chivorns** [comment]
Hi @SalihCanBinboga , your request has been done in version 1.2.1. Please enjoy!

**Comment by SalihCanBinboga** [comment]
@Chivorns 
Yes that's work! Thank you

**Comment by Chivorns** [comment]
You're welcome.
