### ISSUE TITLE
Unable to change the list background color

### ISSUE THREAD

**Issue by mooglife** [Chivorns/SmartMaterialSpinner#15]
Hi there, 

great work!! Thanks. 

I am unable to change the background color (in xml nor in java class), 

This may not be an issue, maybe I missed something. but could you please suggest how I can achieve it? 

Attached is the screenshot.

Best 
Vij

![screenshot](https://user-images.githubusercontent.com/33594975/77761704-baa3d500-7038-11ea-9c13-bb45ca50da20.png)

**Comment by Chivorns** [comment]
Hi @mooglife, thank for your support and feedback for this. I will include it to next release soon.
As I am busy with other projects, it might be late for your need.
Please stay tune!

**Comment by Chivorns** [comment]
Hi @mooglife , I have done for this request. I will include it in next release!

**Comment by Chivorns** [comment]
Hi @mooglife , your request is available in release v1.2.1 now. Please enjoy!

**Comment by mooglife** [comment]
Hi @Chivorns, 

great response and support.

Thank you
Vij

**Comment by Chivorns** [comment]
You're welcome.

**Comment by ChildProdigy** [comment]
This problem still exists.
app:smsp_itemListBackgroundColor="@color/white"
not working.
