### ISSUE TITLE
how to use onSearchItemSelected data from api ?

### ISSUE THREAD

**Issue by muriiphone** [Chivorns/SmartMaterialSpinner#16]
how to use onSearchItemSelected data from api ?

**Comment by Chivorns** [comment]
Hi @muriiphone , please use setOnItemSelectedListener(). I will modify onSearchItemSelected() method to private as it is for internal use only.

**Comment by Chivorns** [comment]
Let me know if you understand how to use this method and I will close this issue. Thank
