### ISSUE TITLE
Feature request: outline mode for background.

### ISSUE THREAD

**Issue by nareshkatta99** [Chivorns/SmartMaterialSpinner#17]
In my project we are using all boxed edit texts.
To be in sync with theme,
We have to use outlined boarder instead of filled box.

**Comment by Chivorns** [comment]
Hi @nareshkatta99 and  @deinlandel, I have added this feature and I will release it to version 1.4.0. Now I'm working on another issues to include it together.
To enable outlined mode, you can set `app:smsp_isOutlined="true"` in your layout.
Here is sample you can try:

```
<com.chivorn.smartmaterialspinner.SmartMaterialSpinner
    android:id="@+id/sp_provinces_outlined_style"
    style="@style/spinnerStyle"
    app:smsp_arrowColor="#3da4ab"
    app:smsp_errorText="@string/sample_error_message"
    app:smsp_hint="Outlined Style"
    app:smsp_hintColor="#fe8a71"
    app:smsp_isOutlined="true"
    app:smsp_multilineError="false"
    app:smsp_outlinedBoxColor="#0e9aa7"
    app:smsp_outlinedBoxRadius="12dp"
    app:smsp_outlinedHintPadding="4dp"
    app:smsp_outlinedHintStartX="10dp"
    app:smsp_outlinedStrokeWidth="1dp" />
```

You also can do it programmatically.
Thank you
