### ISSUE TITLE
How to disable hint in dropdown list

### ISSUE THREAD

**Issue by MahaSakka** [Chivorns/SmartMaterialSpinner#19]
I would like to know, If it's possible to remove the hint text after choose the item in the spinner list?

**Comment by Chivorns** [comment]
Hi @MahaSakka , as default behavior it keep hint text even item was selected, so if you want to apply the behavior like this, you can try to set hint to null (ex: `setHint(null)`) in your `onItemSelected()` method.

Let me know if it works or you need more detail on this. Thank you

**Comment by Chivorns** [comment]
Hi @MahaSakka , from version 1.4.0 onward, I will disable dropdown hint by default. 
I you wish to enable it back, you can just use my new attribute `app:smsp_showDropdownHint="true"` and make sure auto select item is false (`app:smsp_autoSelectable="false"` ) if you already added it with true value.

So if you want to disable it base on your request above, you just apply with my latest version from `v1.4.0`  and no need to have more additional code.
Thank you
