### ISSUE TITLE
I am not able to display error 

### ISSUE THREAD

**Issue by nisargdoshi** [Chivorns/SmartMaterialSpinner#2]
Hello,
i found two issues while using this library
1. when i m trying to display show error with spProvince.setError("my error") nothing happen
2. onNothingSelected() not called ever
     how to handle if my spinner have select hint value(default value)?

Thnaks.

**Comment by Chivorns** [comment]
Hi, as I currently in busy with other projects, I will check it soon for this case

**Comment by Chivorns** [comment]
Hi @nisargdoshi your feedback has been fixed in version 1.0.6. Thank for your feedback

**Comment by nisargdoshi** [comment]
hi @Chivorns  thanks for considering feedback will looking forward to work with your library for next project(s).
