### ISSUE TITLE
Item not shown

### ISSUE THREAD

**Issue by khalidabuhayea** [Chivorns/SmartMaterialSpinner#20]
list items not appear when content in arabic.

**Comment by Chivorns** [comment]
Hi @khalidabuhayea , thank for your feedback. Anyway, can you help to send me a part of your implementation for this issue?
Until now, I got 3 feedback about this issue but the feedback is not clear enough for me to check it.
Hope you detail on this so I will check it for you as soon as possible.
Thank you

**Comment by khalidabuhayea** [comment]
Container(
                      margin: EdgeInsets.only(top: 10),
                      child: DropdownSearch<Language>(
                        showSelectedItem: false,
                        items: languages,
                        mode: Mode.BOTTOM_SHEET,
                        isFilteredOnline: true,
                        showClearButton: true,
                        showSearchBox: true,
                        searchBoxDecoration: new InputDecoration(
                            hintText: "search",
                            icon: new Icon(Icons.search,
                                color: Constants.BorderColor)),
                        label: "Select language",
                        hint: "Select language",
                        itemAsString: (Language u) => u.Name,
                        onChanged: (Language data) => language = data.Id,
                      ),
                    )

**Comment by Chivorns** [comment]
Hi @khalidabuhayea , let me close this as no more details information and it working fine from my side.
