### ISSUE TITLE
IndexOutOfBoundsExceptions when calling SmartMaterialSpinner#setSelection method

### ISSUE THREAD

**Issue by mochadwi** [Chivorns/SmartMaterialSpinner#24]
I'm curious about this line of code (highlighted)
<img width="830" alt="Screen Shot 2020-05-08 at 9 44 05 AM" src="https://user-images.githubusercontent.com/7057959/81364700-7ebc5f00-9110-11ea-94da-3c36304309b0.png">

and see the implementation of `hint` will never be null, because you were always using `""` a blanks/empty strings.
<img width="1302" alt="Screen Shot 2020-05-08 at 9 42 51 AM" src="https://user-images.githubusercontent.com/7057959/81364673-6b10f880-9110-11ea-8cf2-1664d94d3932.png">
both in setter line [1106](https://github.com/Chivorns/SmartMaterialSpinner/blob/master/smartmaterialspinner/src/main/java/com/chivorn/smartmaterialspinner/SmartMaterialSpinner.java#L1106) and [256](https://github.com/Chivorns/SmartMaterialSpinner/blob/master/smartmaterialspinner/src/main/java/com/chivorn/smartmaterialspinner/SmartMaterialSpinner.java#L256)

thus the code:
`SmartMaterialSpinner.super.setSelection(hint != null ? finalPosition + 1 : finalPosition, false);`

will always having a `finalPosition + 1` means the index/position == item.size, `IndexOutOfBoundsExceptions` occurred

IMHO the rest of the nullability check will having a false-positive instead

cmiiw

**Comment by Chivorns** [comment]
Hi @mochadwi , thank for your feedback. I will check on it soon if it the root cause of that issue. Currently I'm a bit busy with company projects so cannot support you for now.
Please stay tune. Thank

**Comment by mochadwi** [comment]
If it's okay, I might open a PR for itu @Chivorns

**Comment by Chivorns** [comment]
Okay @mochadwi . Much appreciate.
