### ISSUE TITLE
How to put a parent class in styles.xml for applying the style to all the material spinners available.

### ISSUE THREAD

**Issue by akhilsreekar** [Chivorns/SmartMaterialSpinner#27]

**Comment by Chivorns** [comment]
Hi @akhilsreekar , please define style with sample bellow:
`<style name="smartmaterialspiiner_style">
        <item name="smsp_hintColor">#B1C025</item>
        <item name="smsp_underlineSize">0.5dp</item>
    </style>`

**Comment by Chivorns** [comment]
Hi @akhilsreekar , Is it what you need?

**Comment by Chivorns** [comment]
Let me close this and please re-open it again if it not resolve your problem. Thank you

**Comment by akhilsreekar** [comment]
Yes...That is what I needed...Thank you
