### ISSUE TITLE
How to prevent keyboard from showing right from the start in searchable spinner?

### ISSUE THREAD

**Issue by deinlandel** [Chivorns/SmartMaterialSpinner#30]
Hello.

Is there a way to prevent keyboard from opening right after searchable spinner is shown? I would like it to be shown when user manually clicks in the search field

**Comment by Chivorns** [comment]
Hi @deinlandel , thank for good question and feedback. Actually it already under my revise list which will be added to next release brother. I set it to show popup keyboard cuz I assume that user will apply to the long list of item. So it is long to scroll and find it then I decide to show it up by default.
Please stay tune for next release brother.
Thank

**Comment by deinlandel** [comment]
@Chivorns Thanks for the reply. Do you know any workaround? Can I somehow hack it using current version of the library? We need to release soon and our UI testers demand that keyboard should not be shown.

**Comment by Chivorns** [comment]
Hi @deinlandel , yeah I have solution for you if you want to custom it by yourself.
In class SearchableSpinnerDialog, please add this one line under existing config.

` searchView.clearFocus();`

Example:

```
searchView.setIconifiedByDefault(false);
searchView.setOnQueryTextListener(this);
searchView.setOnCloseListener(this);
searchView.setFocusable(true);
searchView.setIconified(false);
searchView.requestFocusFromTouch();
searchView.clearFocus(); // New line here
```

As of now I'm not yet full available to update this library, please use this solution first. Thank you.
Let me know if it working brother.

**Comment by deinlandel** [comment]
@Chivorns yeah, I already forked the library and figured the similar solution:
https://github.com/deinlandel/SmartMaterialSpinner/commit/957ce5ada54cf9298b9dd1f99ac1dfc6d9d78561
Anyways, it wasn't enough, I had to add special patch for Android 23 devices:
https://github.com/deinlandel/SmartMaterialSpinner/commit/047413e5e2f097d4c25b366e6f3bed42e2bb6266

**Comment by Chivorns** [comment]
Great @deinlandel .

**Comment by Chivorns** [comment]
Hi @deinlandel , now you can apply this feature by using two options bellow:
### XML
`app:smsp_showKeyboardOnStart="false"`

### Programmatically
`setShowKeyboardOnStart(false)`

### Note: 
I just set default value to `false` for now. You will able to use this feature start from version v1.4.0 onward.
Thank for your request and I just back to support some requests and I will include all of them together.
