### ISSUE TITLE
Preselect an item on the itemList

### ISSUE THREAD

**Issue by james04gr** [Chivorns/SmartMaterialSpinner#34]
I use the spinner inside a Fragment. When i choose an item from the list i navigate to another Fragment. I want to load the last state when i get back to the initial Fragment. Is there any method to load a specific item from the list programmatically?

**Comment by nithinmurali** [comment]
use ```setSelection(index)```

**Comment by Chivorns** [comment]
Hi @james04gr , please use ` spinner.setSelection(specificItemIndex);`
