### ISSUE TITLE
Raw use of parameterized class 'SmartMaterialSpinner' 

### ISSUE THREAD

**Issue by givver** [Chivorns/SmartMaterialSpinner#35]
I am using Android Studio 4.1 with targetSDKVersion 30

I am getting a lint check message of:
	Raw use of parameterized class 'SmartMaterialSpinner' 
	Class SmartMaterialSpinner<T>
	java.lang.Object
	AppCompatSpinner
	com.chivorn.smartmaterialspinner.SmartMaterialSpinner<T>

When I use the following code:
private int getIndex(SmartMaterialSpinner spinner, String item) {
        int index = -1;
        for (int i = 0; i < spinner.getCount(); i++) {
            if (spinner.getItemAtPosition(i).equals(item)) {
                index = i;
                break;
            }
        }
        return index;
    }

The warning highlights "SmartMaterialSpinner"

Am I doing something wrong or is it Android Studio that is giving me a false warning?

**Comment by Chivorns** [comment]
Hi @givver , thank for your feedback. As I plan to make it support generic type, please specify type you want to make it support. You can use String or Object base on your requirement.
Please find my sample code bellow:
```
private int getIndex(SmartMaterialSpinner<Object> spinner, String item) {
    int index = -1;
    for (int i = 0; i < spinner.getCount(); i++) {
        if (spinner.getItemAtPosition(i).equals(item)) {
            index = i;
            break;
        }
    }
    return index;
}
```

Or

```
private int getIndex(SmartMaterialSpinner<String> spinner, String item) {
    int index = -1;
    for (int i = 0; i < spinner.getCount(); i++) {
        if (spinner.getItemAtPosition(i).equals(item)) {
            index = i;
            break;
        }
    }
    return index;
}
```
