### ISSUE TITLE
Selected item highlight color stays on same index even after search filter

### ISSUE THREAD

**Issue by Flamarial** [Chivorns/SmartMaterialSpinner#43]
To reproduce the issue, set a list of items on a searchable SmartMaterialSpinner, then select the first one. The first item in the list is highlighted, since it is selected. Begin to search the list by typing a single character in the search input, and the list updates due to the search filter. However, after doing so, the first item in the list is still highlighted, even though it is not currently the actual selected item. It only seems to care about the index of the selected item from before the search input.

**Comment by Chivorns** [comment]
Thank @Flamarial for your feedback. I already fixed it. I will include it in my next release

**Comment by Flamarial** [comment]
Thank you! Fantastic work you've been doing with this library. I appreciate your vigilance and hard work.

**Comment by Chivorns** [comment]
Hi @Flamarial , you can try with my new version 1.3.0 now. Thank you

**Comment by Flamarial** [comment]
Looks like it works great. One thing I did notice though is that when using `setSelected()` on a searchable spinner, the selected item highlight doesn't work until after manually clicking an item. Non-searchable spinners highlight correctly with `setSelected()`, however. Not a huge deal, but just thought I would give a heads up. Thanks again!
