### ISSUE TITLE
How to change searchtext color?

### ISSUE THREAD

**Issue by arifhakkim** [Chivorns/SmartMaterialSpinner#5]
Currently, my background and text colors of my search box are white. How to change it?

**Comment by Chivorns** [comment]
Hi @arifhakkim I will add more attrs and method to be able to apply with your requirement

**Comment by Chivorns** [comment]
Hi @arifhakkim . I already added new methods and attrs in release v1.1.6.
You can try with attrs:
`- smsp_searchHintColor`
`- smsp_searchTextColor`

or programmatically:
`- setSearchHintColor(int color)`
`- setSearchTextColor(int color)`
`- setSearchBackgroundColor(int color)`
`- setSearchBackgroundColor(Drawable drawable)`

If you found any other issues please let me know.
Thank you

**Comment by TurtleTower** [comment]
Thanks!

**Comment by TurtleTower** [comment]
Would be cool to enable searchHeader without a searchbox! :)
