### ISSUE TITLE
ItemSelectedListener Problem

### ISSUE THREAD

**Issue by khallid-itdevtech** [Chivorns/SmartMaterialSpinner#50]
`spinner.setSelection(0)`
`spinner.onItemSelectedListener =
            (object : AdapterView.OnItemSelectedListener {
                override fun onItemSelected(parent: AdapterView<*>?,  view: View?,    position: Int,
                    id: Long
                ) {
                    //Toast
                    }
                }
                override fun onNothingSelected(parent: AdapterView<*>?) {
                }
            })`
Toast is shown without Item Click inside onCreate() method
I have find that SetSelection() method use Runable to select while your listener is registered and OnItemSelected() called by the listener because of SetSelection() delay.

**Comment by Chivorns** [comment]
Hi @khallid-itdevtech , may u help to provide your xml layout?
I think you also can try to check my sample project if it can help you

**Comment by Chivorns** [comment]
Hi @khallid-itdevtech , let me close this. For any further issue related to this you can open it again. Thank you!!
