### ISSUE TITLE
How to disable spinner

### ISSUE THREAD

**Issue by VrutalDeveloper** [Chivorns/SmartMaterialSpinner#6]
how can i disable touch/click event to pop up dropdown/dialog itemsview
i've tried setEnabled(false) and setClickable(false) but no luck

**Comment by Chivorns** [comment]
Hi @VrutalDeveloper , thank for your feedback. Let me check and back to you later.
But I have other way for you in case you don't want it show popup when it has no item but you want to set event on it you can try to use method setOnEmptySpinnerClickListener().
For example: 

  spinner.setOnEmptySpinnerClickListener(new SmartMaterialSpinner.OnEmptySpinnerClickListener() {
                @Override
                public void onEmptySpinnerClicked() {
                    Toast.makeText(MainActivity.this, getString(R.string.empty_item_spinner_click_msg), Toast.LENGTH_SHORT).show();
                }
            });

**Comment by Chivorns** [comment]
Hi @VrutalDeveloper . This issue already fixed in release v1.1.6.
If you found any other issues please let me know.
Thank you.
