### ISSUE TITLE
Change item textSize

### ISSUE THREAD

**Issue by ShamsEldeenAnd** [Chivorns/SmartMaterialSpinner#7]
how to change item Text size ?

**Comment by Chivorns** [comment]
Hi @ShamsEldeenAnd you can set item text size by two option:
1. xml: smsp_itemSize
2. by code: setItemSize()

And if you want to set hint size, you also can apply with:
1. xml: smsp_hintSize
2. by code: setHintSize()

If this is what you need and it work, please let me know. Thank you.

**Comment by H4zh4n** [comment]
Hey @Chivorns,
A year too late, but none of those two attributes seem to change the items text size in list of items of opened dialog.
would love to know how to change the size of the items when the list is opened.

- `smsp_itemSize` seems to change the selected item size (not in the list - but before opening the list) and the overall shape of View.
- `smsp_hintSize` does what it does. only works for hint.
