### ISSUE TITLE
How to dismiss the search dialog ..?

### ISSUE THREAD

**Issue by amicusindia** [Chivorns/SmartMaterialSpinner#9]

**Comment by Chivorns** [comment]
Hi @amicusindia , currently it is possible only when you press back button. There is no method or attr to enable dismiss icon or dismiss on touch outside of dialog. I will consider to add it in next improvement. Thank you

**Comment by Chivorns** [comment]
Hi @amicusindia , your request has been added in version 1.2.1. Please enjoy!
